version: '3'
services:
  database:
    image: postgres
    container_name: "test_postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - car_sharing
  
  backend:
    container_name: "car_sharing_backend"
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./env/.env
    ports:
      - "4000:3000"
    depends_on:
      - database
    networks:
      - car_sharing

networks:
  car_sharing: